//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İkinciElKitap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitap()
        {
            this.Sepets = new HashSet<Sepet>();
        }
    
        public int KitapID { get; set; }
        public string KitapAd { get; set; }
        public Nullable<int> SayfaSayisi { get; set; }
        public Nullable<System.DateTime> YayimlanmaTarihi { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string ResimURL { get; set; }
        public Nullable<int> YayineviID { get; set; }
        public Nullable<int> StokID { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> YazarID { get; set; }
        public Nullable<int> SaticiID { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Satici Satici { get; set; }
        public virtual Stok Stok { get; set; }
        public virtual Yayinevi Yayinevi { get; set; }
        public virtual Yazar Yazar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepets { get; set; }
    }
}
