//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İkinciElKitap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int SepetID { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public Nullable<int> KitapID { get; set; }
        public Nullable<int> AliciID { get; set; }
    
        public virtual Kitap Kitap { get; set; }
        public virtual Sipari Sipari { get; set; }
        public virtual Alici Alici { get; set; }
    }
}
