//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İkinciElKitap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sipari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sipari()
        {
            this.Sepets = new HashSet<Sepet>();
        }
    
        public int SiparisID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> AliciID { get; set; }
    
        public virtual Alici Alici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepets { get; set; }
    }
}
